//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BethesdaCarRental1.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.RentalOrders = new HashSet<RentalOrder>();
        }

        [Display(Name = "Car ID")]
        public int CarID { get; set; }
        [Display(Name = "Tag #")]
        public string TagNumber { get; set; }
        public string Category { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Passengers { get; set; }
        public string Condition { get; set; }
        [Display(Name = "Availability Status")]
        public string AvailabilityStatus { get; set; }

        public string Vehicle
        {
            get
            {
                return TagNumber + " - " + Make + " " + Model + " (" + Category + ", " + Condition + ", " + AvailabilityStatus + ")";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalOrder> RentalOrders { get; set; }
    }
}
