//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BethesdaCarRental1.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RentalOrder
    {
        [Display(Name = "Rental Order ID")]
        public int RentalOrderID { get; set; }
        [Display(Name = "Processed By")]
        public int EmployeeID { get; set; }
        [Display(Name = "Customer Drv. Lic. #")]
        public string DriversLicenseNumber { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        [Display(Name = "ZIP Code")]
        public string ZIPCode { get; set; }
        [Display(Name = "Car Selected")]
        public Nullable<int> CarID { get; set; }
        [Display(Name = "Car Condition")]
        public string CarCondition { get; set; }
        [Display(Name = "Tank Level")]
        public string TankLevel { get; set; }
        [Display(Name = "Mileage Start")]
        public string MileageStart { get; set; }
        [Display(Name = "Mileage End")]
        public string MileageEnd { get; set; }
        [Display(Name = "Mileage Total")]
        public string MileageTotal { get; set; }
        [Display(Name = "Start Date")]
        public string StartDate { get; set; }
        [Display(Name = "End Date")]
        public string EndDate { get; set; }
        [Display(Name = "Total Days")]
        public string TotalDays { get; set; }
        [Display(Name = "Rate Applied")]
        public string RateApplied { get; set; }
        [Display(Name = "Sub-Total")]
        public string SubTotal { get; set; }
        [Display(Name = "Tax Rate")]
        public string TaxRate { get; set; }
        [Display(Name = "Tax Amount")]
        public string TaxAmount { get; set; }
        [Display(Name = "Order Total")]
        public string OrderTotal { get; set; }
        [Display(Name = "Payment Date")]
        public string PaymentDate { get; set; }
        [Display(Name = "Order Status")]
        public string OrderStatus { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
